#!/bin/bash
T=$1
N=`echo ${T:0:1} | tr '[:lower:]' '[:upper:]'`${T:1}
ST=${N}Sequence
IT=`echo ${T:0:1} | tr '[:upper:]' '[:lower:]'`${T:1}Iterator
CMP=$2
FN=zz_generated.$T.go
echo Generating $FN
cat <<EOF >$FN
// Code generated by genseqs.sh. DO NOT EDIT.
/*
adammil.net/collections is a library that implements .NET-like collection
interfaces for Go.

http://www.adammil.net/
Copyright (C) 2019 Adam Milazzo

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

package collections

import "reflect"

type $ST []$T

var _ List = $ST{}

func init() {
	RegisterSequenceCreator(reflect.TypeOf([]$T{}), func(obj T) (Sequence,error) {
		return $ST(obj.([]$T)), nil
	})
}

func (s $ST) Iterator() Iterator {
	return &$IT{s,-1}
}

func (s $ST) Count() int {
	return len(s)
}

func (s $ST) Get(index int) T {
	return s[index]
}

func (s $ST) Set(index int, value T) {
	s[index] = value.($T)
}

type $IT struct {
	array []$T
	index int
}

func (i *$IT) Current() T {
	return i.array[i.index]
}

func (i *$IT) Next() bool {
	ni := i.index + 1
	if ni < len(i.array) {
		i.index = ni
		return true
	}
	return false
}

func (s $ST) Contains(item T) bool {
	return s.IndexOf(item) >= 0
}
EOF

if [[ "$T" != "T" ]]; then
	cat <<EOF >>$FN

func (s $ST) IndexOf(item T) int {
	if v, ok := item.($T); ok {
		for i, sv := range s {
			if sv == v {
				return i
			}
		}
	}
	return -1
}

func ${N}EqualFunc(a, b T) bool {
	return a.($T) == b.($T)
}
EOF
else
	cat <<EOF >>$FN

func (s $ST) IndexOf(item T) int {
	cmp := makeContainsComparer(item)
	for i, v := range s {
		if cmp.Equal(v) {
			return i
		}
	}
	return -1
}

func (s $ST) Len() int {
	return len(s)
}

func (s $ST) Less(ai, bi int) bool {
	return GenericLessThan(s[ai], s[bi])
}

func (s $ST) Swap(ai, bi int) {
	s[ai], s[bi] = s[bi], s[ai]
}
EOF
fi

if [[ -n "$CMP" ]]; then
	cat <<EOF >>$FN

func ${N}LessThanFunc(a, b T) bool {
	return a.($T) < b.($T)
}

func (s $ST) Len() int {
	return len(s)
}

func (s $ST) Less(ai, bi int) bool {
	return s[ai] < s[bi]
}

func (s $ST) Swap(ai, bi int) {
	s[ai], s[bi] = s[bi], s[ai]
}
EOF
fi
