// Code generated by genseqs.sh. DO NOT EDIT.
/*
adammil.net/collections is a library that implements .NET-like collection
interfaces for Go.

http://www.adammil.net/
Copyright (C) 2019 Adam Milazzo

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

package collections

import "reflect"

type Uint8Sequence []uint8

var _ List = Uint8Sequence{}

func init() {
	RegisterSequenceCreator(reflect.TypeOf([]uint8{}), func(obj T) (Sequence,error) {
		return Uint8Sequence(obj.([]uint8)), nil
	})
}

func (s Uint8Sequence) Iterator() Iterator {
	return &uint8Iterator{s,-1}
}

func (s Uint8Sequence) Count() int {
	return len(s)
}

func (s Uint8Sequence) Get(index int) T {
	return s[index]
}

func (s Uint8Sequence) Set(index int, value T) {
	s[index] = value.(uint8)
}

type uint8Iterator struct {
	array []uint8
	index int
}

func (i *uint8Iterator) Current() T {
	return i.array[i.index]
}

func (i *uint8Iterator) Next() bool {
	ni := i.index + 1
	if ni < len(i.array) {
		i.index = ni
		return true
	}
	return false
}

func (s Uint8Sequence) Contains(item T) bool {
	if v, ok := item.(uint8); ok {
		for i := 0; i < len(s); i++ {
			if s[i] == v {
				return true
			}
		}
	}
	return false
}

func Uint8EqualFunc(a, b T) bool {
	return a.(uint8) == b.(uint8)
}

func Uint8LessThanFunc(a, b T) bool {
	return a.(uint8) < b.(uint8)
}

func (s Uint8Sequence) Len() int {
	return len(s)
}

func (s Uint8Sequence) Less(ai, bi int) bool {
	return s[ai] < s[bi]
}

func (s Uint8Sequence) Swap(ai, bi int) {
	s[ai], s[bi] = s[bi], s[ai]
}
