// Code generated by genseqs.sh. DO NOT EDIT.
/*
adammil.net/collections is a library that implements .NET-like collection
interfaces for Go.

http://www.adammil.net/
Copyright (C) 2019 Adam Milazzo

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

package collections

import "reflect"

type UintSequence []uint

var _ List = UintSequence{}

func init() {
	RegisterSequenceCreator(reflect.TypeOf([]uint{}), func(obj T) (Sequence,error) {
		return UintSequence(obj.([]uint)), nil
	})
}

func (s UintSequence) Iterator() Iterator {
	return &uintIterator{s,-1}
}

func (s UintSequence) Count() int {
	return len(s)
}

func (s UintSequence) Get(index int) T {
	return s[index]
}

func (s UintSequence) Set(index int, value T) {
	s[index] = value.(uint)
}

type uintIterator struct {
	array []uint
	index int
}

func (i *uintIterator) Current() T {
	return i.array[i.index]
}

func (i *uintIterator) Next() bool {
	ni := i.index + 1
	if ni < len(i.array) {
		i.index = ni
		return true
	}
	return false
}

func (s UintSequence) Contains(item T) bool {
	if v, ok := item.(uint); ok {
		for i := 0; i < len(s); i++ {
			if s[i] == v {
				return true
			}
		}
	}
	return false
}

func UintEqualFunc(a, b T) bool {
	return a.(uint) == b.(uint)
}

func UintLessThanFunc(a, b T) bool {
	return a.(uint) < b.(uint)
}

func (s UintSequence) Len() int {
	return len(s)
}

func (s UintSequence) Less(ai, bi int) bool {
	return s[ai] < s[bi]
}

func (s UintSequence) Swap(ai, bi int) {
	s[ai], s[bi] = s[bi], s[ai]
}
