// Code generated by genseqs.sh. DO NOT EDIT.
/*
adammil.net/collections is a library that implements .NET-like collection
interfaces for Go.

http://www.adammil.net/
Copyright (C) 2019 Adam Milazzo

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

package collections

import "reflect"

type IntSequence []int

var _ List = IntSequence{}

func init() {
	RegisterSequenceCreator(reflect.TypeOf([]int{}), func(obj T) (Sequence,error) {
		return IntSequence(obj.([]int)), nil
	})
}

func (s IntSequence) Iterator() Iterator {
	return &intIterator{s,-1}
}

func (s IntSequence) Count() int {
	return len(s)
}

func (s IntSequence) Get(index int) T {
	return s[index]
}

func (s IntSequence) Set(index int, value T) {
	s[index] = value.(int)
}

type intIterator struct {
	array []int
	index int
}

func (i *intIterator) Current() T {
	return i.array[i.index]
}

func (i *intIterator) Next() bool {
	ni := i.index + 1
	if ni < len(i.array) {
		i.index = ni
		return true
	}
	return false
}

func (s IntSequence) Contains(item T) bool {
	return s.IndexOf(item) >= 0
}

func (s IntSequence) IndexOf(item T) int {
	if v, ok := item.(int); ok {
		for i, sv := range s {
			if sv == v {
				return i
			}
		}
	}
	return -1
}

func IntEqualFunc(a, b T) bool {
	return a.(int) == b.(int)
}

func IntLessThanFunc(a, b T) bool {
	return a.(int) < b.(int)
}

func (s IntSequence) Len() int {
	return len(s)
}

func (s IntSequence) Less(ai, bi int) bool {
	return s[ai] < s[bi]
}

func (s IntSequence) Swap(ai, bi int) {
	s[ai], s[bi] = s[bi], s[ai]
}
