// Code generated by genseqs.sh. DO NOT EDIT.
/*
adammil.net/collections is a library that implements .NET-like collection
interfaces for Go.

http://www.adammil.net/
Copyright (C) 2019 Adam Milazzo

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

package collections

import "reflect"

type StringSequence []string

var _ List = StringSequence{}

func init() {
	RegisterSequenceCreator(reflect.TypeOf([]string{}), func(obj T) (Sequence,error) {
		return StringSequence(obj.([]string)), nil
	})
}

func (s StringSequence) Iterator() Iterator {
	return &stringIterator{s,-1}
}

func (s StringSequence) Count() int {
	return len(s)
}

func (s StringSequence) Get(index int) T {
	return s[index]
}

func (s StringSequence) Set(index int, value T) {
	s[index] = value.(string)
}

type stringIterator struct {
	array []string
	index int
}

func (i *stringIterator) Current() T {
	return i.array[i.index]
}

func (i *stringIterator) Next() bool {
	ni := i.index + 1
	if ni < len(i.array) {
		i.index = ni
		return true
	}
	return false
}

func (s StringSequence) Contains(item T) bool {
	return s.IndexOf(item) >= 0
}

func (s StringSequence) IndexOf(item T) int {
	if v, ok := item.(string); ok {
		for i, sv := range s {
			if sv == v {
				return i
			}
		}
	}
	return -1
}

func StringEqualFunc(a, b T) bool {
	return a.(string) == b.(string)
}

func StringLessThanFunc(a, b T) bool {
	return a.(string) < b.(string)
}

func (s StringSequence) Len() int {
	return len(s)
}

func (s StringSequence) Less(ai, bi int) bool {
	return s[ai] < s[bi]
}

func (s StringSequence) Swap(ai, bi int) {
	s[ai], s[bi] = s[bi], s[ai]
}
