// Code generated by genseqs.sh. DO NOT EDIT.
/*
adammil.net/collections is a library that implements .NET-like collection
interfaces for Go.

http://www.adammil.net/
Copyright (C) 2019 Adam Milazzo

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

package collections

import "reflect"

type Uint64Sequence []uint64

var _ List = Uint64Sequence{}

func init() {
	RegisterSequenceCreator(reflect.TypeOf([]uint64{}), func(obj T) (Sequence,error) {
		return Uint64Sequence(obj.([]uint64)), nil
	})
}

func (s Uint64Sequence) Iterator() Iterator {
	return &uint64Iterator{s,-1}
}

func (s Uint64Sequence) Count() int {
	return len(s)
}

func (s Uint64Sequence) Get(index int) T {
	return s[index]
}

func (s Uint64Sequence) Set(index int, value T) {
	s[index] = value.(uint64)
}

type uint64Iterator struct {
	array []uint64
	index int
}

func (i *uint64Iterator) Current() T {
	return i.array[i.index]
}

func (i *uint64Iterator) Next() bool {
	ni := i.index + 1
	if ni < len(i.array) {
		i.index = ni
		return true
	}
	return false
}

func (s Uint64Sequence) Contains(item T) bool {
	return s.IndexOf(item) >= 0
}

func (s Uint64Sequence) IndexOf(item T) int {
	if v, ok := item.(uint64); ok {
		for i, sv := range s {
			if sv == v {
				return i
			}
		}
	}
	return -1
}

func Uint64EqualFunc(a, b T) bool {
	return a.(uint64) == b.(uint64)
}

func Uint64LessThanFunc(a, b T) bool {
	return a.(uint64) < b.(uint64)
}

func (s Uint64Sequence) Len() int {
	return len(s)
}

func (s Uint64Sequence) Less(ai, bi int) bool {
	return s[ai] < s[bi]
}

func (s Uint64Sequence) Swap(ai, bi int) {
	s[ai], s[bi] = s[bi], s[ai]
}
