// Code generated by genseqs.sh. DO NOT EDIT.
/*
adammil.net/collections is a library that implements .NET-like collection
interfaces for Go.

http://www.adammil.net/
Copyright (C) 2019 Adam Milazzo

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

package collections

import "reflect"

type Complex64Sequence []complex64

var _ List = Complex64Sequence{}

func init() {
	RegisterSequenceCreator(reflect.TypeOf([]complex64{}), func(obj T) (Sequence,error) {
		return Complex64Sequence(obj.([]complex64)), nil
	})
}

func (s Complex64Sequence) Iterator() Iterator {
	return &complex64Iterator{s,-1}
}

func (s Complex64Sequence) Count() int {
	return len(s)
}

func (s Complex64Sequence) Get(index int) T {
	return s[index]
}

func (s Complex64Sequence) Set(index int, value T) {
	s[index] = value.(complex64)
}

type complex64Iterator struct {
	array []complex64
	index int
}

func (i *complex64Iterator) Current() T {
	return i.array[i.index]
}

func (i *complex64Iterator) Next() bool {
	ni := i.index + 1
	if ni < len(i.array) {
		i.index = ni
		return true
	}
	return false
}

func (s Complex64Sequence) Contains(item T) bool {
	if v, ok := item.(complex64); ok {
		for i := 0; i < len(s); i++ {
			if s[i] == v {
				return true
			}
		}
	}
	return false
}

func Complex64EqualFunc(a, b T) bool {
	return a.(complex64) == b.(complex64)
}
