// Code generated by genseqs.sh. DO NOT EDIT.
/*
adammil.net/collections is a library that implements .NET-like collection
interfaces for Go.

http://www.adammil.net/
Copyright (C) 2019 Adam Milazzo

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

package collections

import "reflect"

type Int16Sequence []int16

var _ List = Int16Sequence{}

func init() {
	RegisterSequenceCreator(reflect.TypeOf([]int16{}), func(obj T) (Sequence,error) {
		return Int16Sequence(obj.([]int16)), nil
	})
}

func (s Int16Sequence) Iterator() Iterator {
	return &int16Iterator{s,-1}
}

func (s Int16Sequence) Count() int {
	return len(s)
}

func (s Int16Sequence) Get(index int) T {
	return s[index]
}

func (s Int16Sequence) Set(index int, value T) {
	s[index] = value.(int16)
}

type int16Iterator struct {
	array []int16
	index int
}

func (i *int16Iterator) Current() T {
	return i.array[i.index]
}

func (i *int16Iterator) Next() bool {
	ni := i.index + 1
	if ni < len(i.array) {
		i.index = ni
		return true
	}
	return false
}

func (s Int16Sequence) Contains(item T) bool {
	return s.IndexOf(item) >= 0
}

func (s Int16Sequence) IndexOf(item T) int {
	if v, ok := item.(int16); ok {
		for i, sv := range s {
			if sv == v {
				return i
			}
		}
	}
	return -1
}

func Int16EqualFunc(a, b T) bool {
	return a.(int16) == b.(int16)
}

func Int16LessThanFunc(a, b T) bool {
	return a.(int16) < b.(int16)
}

func (s Int16Sequence) Len() int {
	return len(s)
}

func (s Int16Sequence) Less(ai, bi int) bool {
	return s[ai] < s[bi]
}

func (s Int16Sequence) Swap(ai, bi int) {
	s[ai], s[bi] = s[bi], s[ai]
}
